# ---------------------------------------------------------------------------
# Database (idempotent: creates if not exists, owned by master)
#
# prevent_destroy so unlink (a targeted destroy of the grant resources only,
# see workflows/aws/unlink.yaml) can never drop this database even if the
# module's targets are ever misconfigured — unlink is documented to preserve
# data, and this makes that a Terraform-enforced guarantee, not just a
# targeting convention.
# ---------------------------------------------------------------------------

resource "postgresql_database" "app" {
  name  = var.db_name
  owner = var.master_username

  lifecycle {
    prevent_destroy = true
  }
}

# ---------------------------------------------------------------------------
# App user (password generated by Terraform, stable across re-applies)
# The keepers block ensures the password is only regenerated if link_id
# changes (which it won't), preserving credentials on update workflows.
# ---------------------------------------------------------------------------

resource "random_password" "user" {
  length  = 32
  special = false
  keepers = {
    link_id = var.link_id
  }
}

resource "postgresql_role" "app_user" {
  name     = var.db_username
  password = random_password.user.result
  login    = true
}

# ---------------------------------------------------------------------------
# Permissions
# ---------------------------------------------------------------------------

resource "postgresql_grant" "connect" {
  database    = postgresql_database.app.name
  role        = postgresql_role.app_user.name
  object_type = "database"
  privileges  = ["CONNECT"]
}

resource "postgresql_grant" "schema_usage" {
  database    = postgresql_database.app.name
  role        = postgresql_role.app_user.name
  schema      = "public"
  object_type = "schema"
  privileges  = ["USAGE"]
}

# Grant on existing tables
resource "postgresql_grant" "tables" {
  database    = postgresql_database.app.name
  role        = postgresql_role.app_user.name
  schema      = "public"
  object_type = "table"
  privileges  = local.table_privileges[var.access_level]
}

# Grant on future tables (default privileges applied by master user)
resource "postgresql_default_privileges" "tables" {
  role        = postgresql_role.app_user.name
  database    = postgresql_database.app.name
  schema      = "public"
  owner       = var.master_username
  object_type = "table"
  privileges  = local.table_privileges[var.access_level]
}
